###############################################################################
#
# fw2csv Makefile
# 	Generated by amyznikov Jan 26, 2012
#
###############################################################################

TARGET=fw2csv
all : $(TARGET)

prefix=/usr/local
install_dir=$(prefix)/bin

SOURCES = fw2csv.c
MODULES = $(foreach s,$(SOURCES),$(addsuffix .o,$(basename $(s))))

ifndef cc
cc=gcc
endif


###############################################################################
#
# GCC
#
ifeq ($(strip $(cc)),gcc)

# C preprocessor flags
CPPFLAGS=

# C Compiler and flags
CC=gcc
CFLAGS=-O3 -g0 $(DEFINES) $(INCLUDES)

# Loader Flags And Libraries
LD=$(CC)
LDFLAGS = $(CFLAGS)
LDLIBS +=
endif



###############################################################################
#
# ICC
#
ifeq ($(strip $(cc)),icc)

export LC_CTYPE=C
# C preprocessor flags
CPPFLAGS=

# C Compiler and flags
CC=icc
CFLAGS=-O3 -ftz $(DEFINES) $(INCLUDES)

# Loader Flags And Libraries
LD=$(CC)
LDFLAGS = $(CFLAGS)
LDLIBS +=
endif



###############################################################################

$(TARGET) : $(MODULES)
	$(LD) $(LDFLAGS) -o $@ $(MODULES) $(LDLIBS) && strip --strip-all $(TARGET) 

clean:
	$(RM) $(MODULES)

distclean:
	$(RM) $(MODULES) $(TARGET)

install: $(install_dir)
	cp $(TARGET) $(install_dir)/

$(install_dir):
	mkdir -p $(install_dir)

